---

- hosts: master
  vars:
    peers:
        - 127.0.0.1
        - 192.168.56.1
        - 1.1.2.3
        - 1.1.1.2
  gather_facts: no
  tasks:
  - shell: ping {{ item }} -c 1 -W 1.5
    register: "pong"
    with_items: "{{ peers }}"
    ignore_errors: true
  - shell: 'echo "- \"time\": \"`date "+%Y%m%d_%H%M%S"`\"" >>/tmp/test.txt'
  - shell: 'echo "  \"result\":" >>/tmp/test.txt'
  - shell: "echo \"    - { {{ item.item }}: { rc: {{ item.rc | quote }}, ping_time: \\\"{{ item.stdout_lines[1] | regex_search(\"time=.*ms\") |replace(\"time=\",\"\") }}\\\" } }\" >>/tmp/test.txt"
    with_items: "{{ pong.results }}"
