---

- hosts: master
  vars:
    peers:
        - 127.0.0.1
        - 192.168.56.1
        - 1.1.2.3
        - 1.1.1.2
  gather_facts: no
  tasks:
  - shell: ping {{ item }} -c 1 -W 1.5
    with_items: "{{ peers }}"
